apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-multitenant-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-multitenant-app
  template:
    metadata:
      labels:
        app: my-multitenant-app
    spec:
      containers:
      - name: my-multitenant-app
        image: xamma/my-multitenant-app:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-multitenant-app-service
spec:
  selector:
    app: my-multitenant-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-multitenant-app-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: multitenant.local
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: my-multitenant-app-service
#             port:
#               number: 3000