apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cloud
build:
  artifacts:
    - image: my-multitenant-app
      context: backend/app
      docker:
        dockerfile: Dockerfile
    - image: my-postgres-image
      context: backend/app/sql
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - backend/k8s/my-multitenant-app.yml
    - backend/k8s/my-postgres.yml

