GET http://localhost/maintenance-object/35e7962f-602a-4c68-a074-cbd2ad709997
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInRlbmFudCI6InRlbmFudDEiLCJpYXQiOjE2OTQzNDUwNDYsImV4cCI6MTY5NDM0ODY0Nn0.5SXbtxJe_tDxGnyrNb9PEjb17eIZZF1JmQrc1Ckl-14

###
GET http://localhost/maintenance-object/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInRlbmFudCI6InRlbmFudDEiLCJpYXQiOjE2OTQzNDI5NDYsImV4cCI6MTY5NDM0NjU0Nn0.KawZnaHTClV0xosj4T6qG6u6fRryOt_SCu07PkxE-as

###
GET http://localhost/maintenance-report/2021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInRlbmFudCI6InRlbmFudDEiLCJpYXQiOjE2OTQzNDI5NDYsImV4cCI6MTY5NDM0NjU0Nn0.KawZnaHTClV0xosj4T6qG6u6fRryOt_SCu07PkxE-as

###
POST http://localhost/auth
Content-Type: application/json

{"username": "user1", "password":"password1"}
